### ISSUE TITLE
Crashes Ender Quarry when it attempts to mine a poor ore

### ISSUE THREAD

**Issue by Tergiver** [Xexanos/PoorOres#3]
Discovered when playing Material Energy^4 (v0.7.0). PoorOres-1.7.2-1.3.1. ExtraUtilities-1.2.1.

I setup a quick test to confirm that it is the poor ore that causes the crash. I setup a simple quarry with empty air below it except for a single poor iron ore block.

Also posted a report to ExtraUtilities: https://github.com/rwtema/extrautilities/issues/456

```
---- Minecraft Crash Report ----
// There are four lights!

Time: 12/29/14 11:17 AM
Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
    at com.rwtema.extrautils.tileentity.enderquarry.BlockBreakingRegistry.blackList(BlockBreakingRegistry.java:30)
    at com.rwtema.extrautils.tileentity.enderquarry.TileEntityEnderQuarry.mineBlock(TileEntityEnderQuarry.java:495)
    at com.rwtema.extrautils.tileentity.enderquarry.TileEntityEnderQuarry.func_145845_h(TileEntityEnderQuarry.java:378)
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
    at com.rwtema.extrautils.tileentity.enderquarry.BlockBreakingRegistry.blackList(BlockBreakingRegistry.java:30)
    at com.rwtema.extrautils.tileentity.enderquarry.TileEntityEnderQuarry.mineBlock(TileEntityEnderQuarry.java:495)
    at com.rwtema.extrautils.tileentity.enderquarry.TileEntityEnderQuarry.func_145845_h(TileEntityEnderQuarry.java:378)

-- Block entity being ticked --
Details:
    Name: enderQuarry // com.rwtema.extrautils.tileentity.enderquarry.TileEntityEnderQuarry
    Block type: ID #777 (tile.extrautils:enderQuarry // com.rwtema.extrautils.tileentity.enderquarry.BlockEnderQuarry)
    Block data value: 1 / 0x1 / 0b0001
    Block location: World: (143,13,259), Chunk: (at 15,0,3 in 8,16; contains blocks 128,0,256 to 143,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Actual block type: ID #777 (tile.extrautils:enderQuarry // com.rwtema.extrautils.tileentity.enderquarry.BlockEnderQuarry)
    Actual block data value: 1 / 0x1 / 0b0001
Stacktrace:
    at net.minecraft.world.World.func_72939_s(World.java:1939)
    at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
    Level name: PoorOre Quarry Test
    All players: 1 total; [EntityPlayerMP['Tergiver'/254, l='PoorOre Quarry Test', x=139.46, y=13.96, z=262.63]]
    Chunk stats: ServerChunkCache: 939 Drop: 0
    Level seed: -4803990825008141971
    Level generator: ID 00 - default, ver 1. Features enabled: false
    Level generator options: 
    Level spawn location: World: (0,0,0), Chunk: (at 0,0,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 0 game time, 0 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: ~~ERROR~~ NullPointerException: null
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_11, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 241241912 bytes (230 MB) / 970457088 bytes (925 MB) up to 4116185088 bytes (3925 MB)
    JVM Flags: 6 total; -Xms256M -Xmx4096M -XX:PermSize=256m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -Xmn512M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
    FML: MCP v9.05 FML v7.10.85.1230 Minecraft Forge 10.13.2.1230 57 mods loaded, 57 mods active
    mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.85.1230} [Forge Mod Loader] (forge-1.7.10-10.13.2.1230-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.2.1230} [Minecraft Forge] (forge-1.7.10-10.13.2.1230-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    appliedenergistics2-core{rv1-beta-37} [AppliedEnergistics2 Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    <CoFH ASM>{000} [CoFH ASM Data Initialization] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MobiusCore{1.2.3} [MobiusCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.3.76} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.3.76-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    SciMCLibCore{0.0.0.2} [SciMCLibCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenModsCore{@VERSION@} [OpenModsCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    debug{1.0} [debug] (denseores-1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    battlegear2{1.0.6.3} [Mine & Blade Battlegear 2 - Bullseye] (1.7.10-MB_Battlegear2-Bullseye-1.0.6.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    bspkrsCore{6.14} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WorldStateCheckpoints{1.7.10.r02} [WorldStateCheckpoints] ([1.7.10]WorldStateCheckpoints-client-1.7.10.r02.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    dendrology{1.7.10-0.3.2} [Ancient Trees] (AncientTrees-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    appliedenergistics2{rv1-beta-37} [Applied Energistics 2] (appliedenergistics2-rv1-beta-37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BiblioCraft{1.8.2} [BiblioCraft] (BiblioCraft[v1.8.2][MC1.7.10].jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CoFHCore{1.7.10R3.0.0B9} [CoFH Core] (CoFHCore-[1.7.10]3.0.0B9-41.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalFoundation{1.7.10R1.0.0RC1} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.0.0RC1-13.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThermalExpansion{1.7.10R4.0.0B8} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.0.0B8-23.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    BigReactors{0.4.0A} [Big Reactors] (BigReactors-0.4.0A.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    chisel{2.1.3} [Chisel] (Chisel 2-2.1.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Waila{1.5.5} [Waila] (Waila-1.5.5_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CompactMachines{1.7.10-1.12} [Compact Machines] (compactmachines-1.7.10-1.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnderIO{1.7.10-2.2.4.0} [Ender IO] (EnderIO-1.7.10-2.2.6.0.buffertest.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnderTech{1.7.10-0.3.0.348} [EnderTech] (EnderTech-1.7.10-0.3.0.348.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    EnderZoo{1.7.10-1.0.5.14} [Ender Zoo] (EnderZoo-1.7.10-1.0.5.14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    exnihilo{1.37} [Ex Nihilo] (Ex-Nihilo-1.37.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MetallurgyCore{4.0.4} [Metallurgy Core] (MetallurgyCore-1.7.10-4.0.4.18.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TConstruct{1.7.10-1.8.1.build815} [Tinkers' Construct] (TConstruct-1.7.10-1.8.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Metallurgy{4.0.5} [Metallurgy 4] (Metallurgy-1.7.10-4.0.5.75.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraTiC{0.8.4} [ExtraTiC] (ExtraTiC-1.7.10-1.0.3.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraUtilities{1.2.1} [Extra Utilities] (extrautilities-1.2.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    HoloInventory{1.8.3.86} [HoloInventory] (HoloInventory-1.7.10-1.8.3.86.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    HardcoreQuesting{The Journey (4.2.1)} [Hardcore Questing Mode] (HQM-The Journey (4.2.1).jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    imc{1.6} [Improving Minecraft] (Improving Minecraft-1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    journeymap{5.0.0RC6} [JourneyMap] (JourneyMap5.0.0RC6_Unlimited_MC1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Lockdown{2.0.0} [Lockdown] (Lockdown-universal-1.7.2-2.0.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    minechem{5.0.5.344} [Minechem] (Minechem-1.7.10-5.0.5.344.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    MineTweaker3{3.0.9} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenMods{0.6} [OpenMods] (OpenModsLib-1.7.10-0.6-snapshot-225.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    OpenBlocks{1.3} [OpenBlocks] (OpenBlocks-1.7.10-1.3-snapshot-436.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PerfectSpawn{1.1} [Perfect Spawn] (PerfectSpawn-1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    PoorOres{1.7.10-1.3.1} [PoorOres] (PoorOres-1.7.2-1.3.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Quadrum{1.2.0} [Quadrum] (Quadrum-1.7.10-1.2.0.B13-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    RandomThings{2.2.2} [Random Things] (RandomThings-2.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    santasdecor{0.5.3} [Santa's Decor] (Santa'sDecor-1.7.10-0.5.3.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    SciMCLib{SciMCLib} [SciMCLib] (SciMCLib-1.7.10-0.0.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TiCTooltips{1.1.11b} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.1.11b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Torcherino{1.7s} [Torcherino] (Torcherino-1.7.10-1.7s.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    wailafeatures{0.0.1} [WAILA Features] (WAILA-features-1.7.10-0.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    yampst{1.3.3} [YAMPST] (Yampst-Material Energy^4-1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Ztones{1.7.10} [Ztones] (Ztones-1.7.10-1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    denseores{1.0} [Dense Ores] (denseores-1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IguanaTweaksTConstruct{1.7.10-2.1.0.82} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AE2 Version: beta rv1-beta-37 for Forge 10.13.0.1187
    Mantle Environment: Environment healthy.
    TConstruct Environment: Environment healthy.
    SciMCLib Version: 0.0.0.2
    AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, MJ6:OFF, MJ5:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['Tergiver'/254, l='PoorOre Quarry Test', x=139.46, y=13.96, z=262.63]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'
```

**Comment by Claycorp** [comment]
Moot. Mod updated.
