### ISSUE TITLE
Applying a resource pack fails.

### ISSUE THREAD

**Issue by Nagapito** [Xexanos/PoorOres#6]
When you try to apply a resource pack it fails when registering PoorOres reources...

[15:24:07] [Client thread/INFO]: Caught error stitching, removing all assigned resourcepacks
net.minecraft.util.ReportedException: Registering texture
    at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:91) ~[bqf.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_110549_a(SourceFile:136) ~[bqf.class:?]
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110544_b(SourceFile:104) ~[brg.class:?]
    at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110541_a(SourceFile:92) ~[brg.class:?]
    at net.minecraft.client.Minecraft.func_110436_a(Minecraft.java:598) [bao.class:?]
    at net.minecraft.client.gui.GuiScreenResourcePacks.func_146284_a(SourceFile:151) [bgf.class:?]
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225) [bdw.class:?]
    at net.minecraft.client.gui.GuiScreenResourcePacks.func_73864_a(SourceFile:158) [bgf.class:?]
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296) [bdw.class:?]
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268) [bdw.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1629) [bao.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962) [bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_25]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_25]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.ArrayIndexOutOfBoundsException: Coordinate out of bounds!
    at sun.awt.image.ByteInterleavedRaster.getDataElements(Unknown Source) ~[?:1.8.0_25]
    at java.awt.image.BufferedImage.getRGB(Unknown Source) ~[?:1.8.0_25]
    at net.xexanos.poorores.textures.PoorOreTexture.load(PoorOreTexture.java:104) ~[PoorOreTexture.class:?]
    at net.minecraft.client.renderer.texture.TextureMap.func_110571_b(TextureMap.java:115) ~[bpz.class:?]
    at net.minecraft.client.renderer.texture.TextureMap.func_110551_a(TextureMap.java:90) ~[bpz.class:?]
    at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(SourceFile:72) ~[bqf.class:?]
    ... 27 more

**Comment by Xexanos** [comment]
I think, I narrowed down the problem to happen, when using a resource pack without any textures for PoorOres. I am reworking my code to resize the standard textures of PoorOres.
